### ISSUE TITLE
'403 - forbidden' access in a arm32v6 version of your build

### ISSUE THREAD

**Issue by troymaclure** [jgeusebroek/docker-webdav#6]
Hi.

I built arm/alpine version of your webdav image, importing a "arm32v6/alpine:latest", which is literaly the only line i changed in  your Dockerfile with also the removing of the package version (build date) since there are not the same in the armf repository. 

>FROM arm32v6/alpine:latest
ENV PACKAGE_LIST="lighttpd lighttpd-mod_webdav lighttpd-mod_auth" 
RUN apk add --no-cache ${PACKAGE_LIST}
VOLUME [ "/config", "/webdav" ]
ADD files/* /etc/lighttpd/
ADD ./entrypoint.sh /entrypoint.sh
EXPOSE 80
RUN chmod u+x  /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

Everything build fine fine...

Then I start the container with : 

>docker run \
    --restart=always \
    --name webdav_container_1 \
    -d \
    -p 0.0.0.0:80:80 \
    -e WHITELIST='192.*.*.*' \
    -e READWRITE=true \
    --hostname=webdav \
    --mount source=just_created_volume,target=/webdav \
    piriou/rpi-alpine-webdav

The only difference here being the `--mount source=just_created_volume,target=/webdav` instead of `-v /my/host/folder:/webdav` in your run command in order to contain data in a volume easy to backup.

But once the container is started, my webdav client tell me access is not authorized .

I guess it's a permission issue but i cannot figure out how to fix it. 

I don't know neither if the error is related to the volume i mounted or if it come from your config files or your entrypoint.sh script.

Any idea how to fix that ?

Thank you.

**Comment by troymaclure** [comment]
I made a few change : 
removed `/config` volume (I don't need a separate volume for configuration), removed the need of `WHITELIST`, making people auth everytime, removed `READWRITE` and made the drive writable by default  and, finally, added...

>chown webdav:webdav /webdav

According to the doc i could find, the webdav directory has to be attribuated to the user or the group who will have later access to the drive. It seems it missing from the entrypoint.sh.

As a result, I have now write access to the drive.

**Comment by dudutwizer** [comment]
I know it's old issue, but I'm stuck.
running my docker with 

docker run --restart=always -d -p 0.0.0.0:81:80 --hostname=webdav --name=webdav -v /home/pi/webdav/:/webdav -e -WHITELIST=* -e -READWRITE=true raigen/rpi-alpine-webdav

and still getting 403 error code.

ls inside the conatiner:
drwxrwxrwx    2 webdav   webdav        4096 May  5 21:13 webdav

ls in the host:
drwxrwxrwx  2 2222 2222  4096 May  6 00:13 webdav

Thanks!

**Comment by jgeusebroek** [comment]
Sorry, I can't help you with that. @stephanepiriou might be able to help you.
